### ISSUE TITLE
'show' page for APIs

### ISSUE THREAD

**Issue by joelmahoney** [codeforamerica/open311status#13]
It would be nice to have a page for each API

**Comment by bensheldon** [comment]
I've been working on a rewrite of open311status that includes this feature. Here's the current work:

![screen shot 2018-07-29 at 2 29 54 pm](https://user-images.githubusercontent.com/47554/43370883-eef693a0-933b-11e8-93e0-b9089e80d051.png)

**Comment by bensheldon** [comment]
The rewrite has been merged and this feature is available. Please open new issues if you'd like to see specific things on that page.
