### ISSUE TITLE
Endpoint status services & requests all show error on status.open311.org

### ISSUE THREAD

**Issue by bbrewington** [codeforamerica/open311status#28]
Site - http://status.open311.org/
Screenshot taken: 7/14/18 11:14 AM Eastern
Last scan at Sat Jul 14 2018 15:10:00 GMT+0000 (UTC)

<img width="361" alt="open 311 endpoint scan error" src="https://user-images.githubusercontent.com/10573749/42725744-2e5aed84-8757-11e8-85fc-0f9b11b24ac3.PNG">

**Comment by bensheldon** [comment]
Ooof. Thanks for reporting this. Let me get that fixed.

**Comment by bensheldon** [comment]
Fixed it! It was a little dicey for a moment cause this app hasn't been touched in 4 years. Closed by #31 

<img width="1195" alt="screen shot 2018-07-20 at 5 21 14 pm" src="https://user-images.githubusercontent.com/47554/43030097-66f60c98-8c41-11e8-92f1-d2474600ba6e.png">

Thanks again for opening this issue!
